title:   Métodos de Desenvolvimento de Software
description: > # this means to ignore newlines until "baseurl:"
  Métodos de Desenvolvimento de Software (MDS)
permalink: ':title/'
baseurl: "/projetos" # the subpath of your site, e.g. /blog
url: "https://unb-mds.github.io/portfolio-MDS/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 
author-img: mds.png
about-author: Métodos de Desenvolvimento de Software
social-email:  caguiar@unb.br
social-github: rochacarla

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
